spring.application.name: rest-template-demo

management:  
  endpoints:  
    prometheus:  
      enabled: true  
    web:  
      exposure:  
        include: '*'
  metrics:
    tags:
      application: monitoring
      
logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
  level:
    org.springframework.web.client.RestTemplate: DEBUG
